name: DASTBURP
on:
 push:
   branches: [ master ]
 pull_request:
   branches: [ master ]

steps:
  - name: Run Dastardly Action Step
    uses: PortSwigger/dastardly-github-action@main
    with:
      target-url: 'https://ginandjuice.shop'
